@startuml
left to right direction

actor Anna
actor Laia
actor Marc

rectangle "M5-A12 Aircnc" {

Marc --> (Cercar allotjament)
Marc --> (Fer una reserva)
Marc --> (Fer el pagament)
Marc --> (Aplicar descompte)
Marc --> (Deixar una ressenya)
Marc --> (Contactar amb l'amfitrió)

Laia --> (Acceptar reserva)
Laia --> (Modificar descripció del pis)
Laia --> (Afegir noves fotos)
Laia --> (Ajustar la disponibilitat)

Anna --> (Gestionar ressenyes inadequades)
Anna --> (Gestionar incidències de pagament)

(Fer una reserva) ..> (Fer el pagament) : <<include>>
(Fer el pagament) ..> (Aplicar codi de descompte) : <<include>>
}

@enduml